import { AssignmentRepository, assignmentRepository as defaultRepo } from '../repositories/assignment.repository';
import { JobTracking } from '../models/job-tracking.model';
import { addAssignmentJob } from '../jobs/assignment.job';
import { IAssignment } from '../models/assignment.model';
import { AppError } from '../types/index';
import httpStatus from 'http-status-codes';
import { CacheService, cacheService as defaultCache } from '../lib/cache';
import { GeneratedPaper } from '../models/generated-paper.model';

export class AssignmentService {
  constructor(
    private readonly repo: AssignmentRepository = defaultRepo,
    private readonly cache: CacheService = defaultCache
  ) {}

  /**
   * Create a new assignment and trigger background generation.
   */
  async createAssignment(data: Partial<IAssignment>) {
    // 1. Save to DB
    const assignment = await this.repo.create(data);

    // 2. Enqueue BullMQ job
    await addAssignmentJob({
      assignmentId: (assignment._id as any).toString(),
      subject: assignment.title,
      instructions: assignment.instructions,
      totalQuestions: assignment.totalQuestions,
      questionTypes: assignment.questionTypes,
    });

    // 3. Invalidate list cache
    await this.cache.delByPattern('assignments:list:*');

    return assignment;
  }

  /**
   * Get assignment by ID with its generation status.
   */
  async getAssignmentById(id: string) {
    const cacheKey = `assignment:${id}`;
    
    // Check cache
    const cached = await this.cache.get<any>(cacheKey);
    if (cached) return cached;

    const assignment = await this.repo.findById(id);
    if (!assignment) {
      throw new AppError('Assignment not found', httpStatus.NOT_FOUND);
    }

    // Fetch job tracking info
    const jobId = `assignment-${id}`;
    const jobTracking = await JobTracking.findOne({ jobId });

    // Fetch generated paper (if already generated by workers).
    // GeneratedPaper stores `assignmentId` as an ObjectId reference.
    const generatedPaper = await GeneratedPaper.findOne({ assignmentId: assignment._id });

    const result = {
      assignment,
      jobStatus: jobTracking || null,
      generatedPaper: generatedPaper ? { sections: generatedPaper.sections } : null,
    };

    // Cache the result (shorter TTL if still processing)
    const ttl = (assignment.status === 'completed' || assignment.status === 'failed') ? 600 : 30;
    await this.cache.set(cacheKey, result, ttl);

    return result;
  }

  /**
   * List assignments with pagination.
   */
  async listAssignments(page: number = 1, limit: number = 10) {
    const cacheKey = `assignments:list:${page}:${limit}`;
    
    const cached = await this.cache.get<any>(cacheKey);
    if (cached) return cached;

    const result = await this.repo.findAll({}, { page, limit });
    
    await this.cache.set(cacheKey, result, 300);
    return result;
  }
}

export const assignmentService = new AssignmentService();



